# Generated by Django 2.2.4 on 2021-03-29 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('day_tripper_application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
    ]
