# Generated by Django 2.2.4 on 2021-03-29 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('day_tripper_application', '0002_remove_user_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('difficulty', models.CharField(max_length=255)),
                ('distance', models.IntegerField()),
                ('elevation_change', models.IntegerField()),
                ('route_type', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_date', models.DateField()),
                ('food_list', models.TextField()),
                ('gear_check', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_created', to='day_tripper_application.User')),
                ('joined', models.ManyToManyField(related_name='trips_joined', to='day_tripper_application.User')),
                ('trails', models.ManyToManyField(related_name='trips', to='day_tripper_application.Trail')),
            ],
        ),
    ]
